#############################################################################
# Makefile for building: Schachuhr
# Generated by qmake (2.01a) (Qt 4.7.3) on: Fr. Jul 1 07:19:56 2011
# Project:  Schachuhr.pro
# Template: app
# Command: /home/pscholz/QtSDK/Desktop/Qt/473/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile Schachuhr.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++-64 -I. -I../../QtSDK/Desktop/Qt/473/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/473/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/473/gcc/include/QtTest -I../../QtSDK/Desktop/Qt/473/gcc/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/home/pscholz/QtSDK/Desktop/Qt/473/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/pscholz/QtSDK/Desktop/Qt/473/gcc/lib -lQtTest -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/pscholz/QtSDK/Desktop/Qt/473/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		schachuhr.cpp moc_schachuhr.cpp
OBJECTS       = main.o \
		schachuhr.o \
		moc_schachuhr.o
DIST          = ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf \
		Schachuhr.pro
QMAKE_TARGET  = Schachuhr
DESTDIR       = 
TARGET        = Schachuhr

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_schachuhr.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Schachuhr.pro  ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++-64/qmake.conf ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile Schachuhr.pro
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile Schachuhr.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Schachuhr1.0.0 || $(MKDIR) .tmp/Schachuhr1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Schachuhr1.0.0/ && $(COPY_FILE) --parents schachuhr.h timestruct.h .tmp/Schachuhr1.0.0/ && $(COPY_FILE) --parents main.cpp schachuhr.cpp .tmp/Schachuhr1.0.0/ && $(COPY_FILE) --parents schachuhr.ui .tmp/Schachuhr1.0.0/ && (cd `dirname .tmp/Schachuhr1.0.0` && $(TAR) Schachuhr1.0.0.tar Schachuhr1.0.0 && $(COMPRESS) Schachuhr1.0.0.tar) && $(MOVE) `dirname .tmp/Schachuhr1.0.0`/Schachuhr1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Schachuhr1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_schachuhr.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_schachuhr.cpp
moc_schachuhr.cpp: schachuhr.h
	/home/pscholz/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) schachuhr.h -o moc_schachuhr.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_schachuhr.h
compiler_uic_clean:
	-$(DEL_FILE) ui_schachuhr.h
ui_schachuhr.h: schachuhr.ui
	/home/pscholz/QtSDK/Desktop/Qt/473/gcc/bin/uic schachuhr.ui -o ui_schachuhr.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp schachuhr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

schachuhr.o: schachuhr.cpp schachuhr.h \
		ui_schachuhr.h \
		timestruct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o schachuhr.o schachuhr.cpp

moc_schachuhr.o: moc_schachuhr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_schachuhr.o moc_schachuhr.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

